services:
  - type: web
    name: ocs-categories
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 2 --threads 4 app:app
    envVars:
      - key: OCS_API_KEY
        sync: false