services:
  - type: web
    name: ocs-api
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 20 --workers 1 --preload app:app
    envVars:
      - key: OCS_API_KEY
        value: your_ocs_api_key_here
      - key: FLASK_DEBUG
        value: "False"
      - key: PYTHONUNBUFFERED
        value: "True"